export const JUZ_LIST = [
  { value: "1", label: "Juz 1", startSurah: "Al-Fatihah", startAyat: 1, endSurah: "Al-Baqarah", endAyat: 141 },
  { value: "2", label: "Juz 2", startSurah: "Al-Baqarah", startAyat: 142, endSurah: "Al-Baqarah", endAyat: 252 },
  { value: "3", label: "Juz 3", startSurah: "Al-Baqarah", startAyat: 253, endSurah: "Ali 'Imran", endAyat: 92 },
  { value: "4", label: "Juz 4", startSurah: "Ali 'Imran", startAyat: 93, endSurah: "An-Nisa", endAyat: 23 },
  { value: "5", label: "Juz 5", startSurah: "An-Nisa", startAyat: 24, endSurah: "An-Nisa", endAyat: 147 },
  { value: "6", label: "Juz 6", startSurah: "An-Nisa", startAyat: 148, endSurah: "Al-Ma'idah", endAyat: 81 },
  { value: "7", label: "Juz 7", startSurah: "Al-Ma'idah", startAyat: 82, endSurah: "Al-An'am", endAyat: 110 },
  { value: "8", label: "Juz 8", startSurah: "Al-An'am", startAyat: 111, endSurah: "Al-A'raf", endAyat: 87 },
  { value: "9", label: "Juz 9", startSurah: "Al-A'raf", startAyat: 88, endSurah: "Al-Anfal", endAyat: 40 },
  { value: "10", label: "Juz 10", startSurah: "Al-Anfal", startAyat: 41, endSurah: "At-Tawbah", endAyat: 92 },
  { value: "11", label: "Juz 11", startSurah: "At-Tawbah", startAyat: 93, endSurah: "Hud", endAyat: 5 },
  { value: "12", label: "Juz 12", startSurah: "Hud", startAyat: 6, endSurah: "Yusuf", endAyat: 52 },
  { value: "13", label: "Juz 13", startSurah: "Yusuf", startAyat: 53, endSurah: "Ibrahim", endAyat: 52 },
  { value: "14", label: "Juz 14", startSurah: "Al-Hijr", startAyat: 1, endSurah: "An-Nahl", endAyat: 128 },
  { value: "15", label: "Juz 15", startSurah: "Al-Isra", startAyat: 1, endSurah: "Al-Kahf", endAyat: 74 },
  { value: "16", label: "Juz 16", startSurah: "Al-Kahf", startAyat: 75, endSurah: "Taha", endAyat: 135 },
  { value: "17", label: "Juz 17", startSurah: "Al-Anbiya", startAyat: 1, endSurah: "Al-Hajj", endAyat: 78 },
  { value: "18", label: "Juz 18", startSurah: "Al-Mu'minun", startAyat: 1, endSurah: "Al-Furqan", endAyat: 20 },
  { value: "19", label: "Juz 19", startSurah: "Al-Furqan", startAyat: 21, endSurah: "An-Naml", endAyat: 55 },
  { value: "20", label: "Juz 20", startSurah: "An-Naml", startAyat: 56, endSurah: "Al-'Ankabut", endAyat: 45 },
  { value: "21", label: "Juz 21", startSurah: "Al-'Ankabut", startAyat: 46, endSurah: "Al-Ahzab", endAyat: 30 },
  { value: "22", label: "Juz 22", startSurah: "Al-Ahzab", startAyat: 31, endSurah: "Ya-Sin", endAyat: 27 },
  { value: "23", label: "Juz 23", startSurah: "Ya-Sin", startAyat: 28, endSurah: "Az-Zumar", endAyat: 31 },
  { value: "24", label: "Juz 24", startSurah: "Az-Zumar", startAyat: 32, endSurah: "Fussilat", endAyat: 46 },
  { value: "25", label: "Juz 25", startSurah: "Fussilat", startAyat: 47, endSurah: "Al-Jathiyah", endAyat: 37 },
  { value: "26", label: "Juz 26", startSurah: "Al-Ahqaf", startAyat: 1, endSurah: "Adh-Dhariyat", endAyat: 30 },
  { value: "27", label: "Juz 27", startSurah: "Adh-Dhariyat", startAyat: 31, endSurah: "Al-Hadid", endAyat: 29 },
  { value: "28", label: "Juz 28", startSurah: "Al-Mujadila", startAyat: 1, endSurah: "At-Tahrim", endAyat: 12 },
  { value: "29", label: "Juz 29", startSurah: "Al-Mulk", startAyat: 1, endSurah: "Al-Mursalat", endAyat: 50 },
  { value: "30", label: "Juz 30", startSurah: "An-Naba", startAyat: 1, endSurah: "An-Nas", endAyat: 6 },
]

export const SURAH_LIST = [
  { number: 1, name: "Al-Fatihah", ayatCount: 7 },
  { number: 2, name: "Al-Baqarah", ayatCount: 286 },
  { number: 3, name: "Ali 'Imran", ayatCount: 200 },
  { number: 4, name: "An-Nisa", ayatCount: 176 },
  { number: 5, name: "Al-Ma'idah", ayatCount: 120 },
  { number: 6, name: "Al-An'am", ayatCount: 165 },
  { number: 7, name: "Al-A'raf", ayatCount: 206 },
  { number: 8, name: "Al-Anfal", ayatCount: 75 },
  { number: 9, name: "At-Tawbah", ayatCount: 129 },
  { number: 10, name: "Yunus", ayatCount: 109 },
  { number: 11, name: "Hud", ayatCount: 123 },
  { number: 12, name: "Yusuf", ayatCount: 111 },
  { number: 13, name: "Ar-Ra'd", ayatCount: 43 },
  { number: 14, name: "Ibrahim", ayatCount: 52 },
  { number: 15, name: "Al-Hijr", ayatCount: 99 },
  { number: 16, name: "An-Nahl", ayatCount: 128 },
  { number: 17, name: "Al-Isra", ayatCount: 111 },
  { number: 18, name: "Al-Kahf", ayatCount: 110 },
  { number: 19, name: "Maryam", ayatCount: 98 },
  { number: 20, name: "Taha", ayatCount: 135 },
  { number: 21, name: "Al-Anbiya", ayatCount: 112 },
  { number: 22, name: "Al-Hajj", ayatCount: 78 },
  { number: 23, name: "Al-Mu'minun", ayatCount: 118 },
  { number: 24, name: "An-Nur", ayatCount: 64 },
  { number: 25, name: "Al-Furqan", ayatCount: 77 },
  { number: 26, name: "Asy-Syu'ara", ayatCount: 227 },
  { number: 27, name: "An-Naml", ayatCount: 93 },
  { number: 28, name: "Al-Qasas", ayatCount: 88 },
  { number: 29, name: "Al-'Ankabut", ayatCount: 69 },
  { number: 30, name: "Ar-Rum", ayatCount: 60 },
  { number: 31, name: "Luqman", ayatCount: 34 },
  { number: 32, name: "As-Sajdah", ayatCount: 30 },
  { number: 33, name: "Al-Ahzab", ayatCount: 73 },
  { number: 34, name: "Saba", ayatCount: 54 },
  { number: 35, name: "Fatir", ayatCount: 45 },
  { number: 36, name: "Ya-Sin", ayatCount: 83 },
  { number: 37, name: "As-Saffat", ayatCount: 182 },
  { number: 38, name: "Sad", ayatCount: 88 },
  { number: 39, name: "Az-Zumar", ayatCount: 75 },
  { number: 40, name: "Ghafir", ayatCount: 85 },
  { number: 41, name: "Fussilat", ayatCount: 54 },
  { number: 42, name: "Asy-Syura", ayatCount: 53 },
  { number: 43, name: "Az-Zukhruf", ayatCount: 89 },
  { number: 44, name: "Ad-Dukhan", ayatCount: 59 },
  { number: 45, name: "Al-Jathiyah", ayatCount: 37 },
  { number: 46, name: "Al-Ahqaf", ayatCount: 35 },
  { number: 47, name: "Muhammad", ayatCount: 38 },
  { number: 48, name: "Al-Fath", ayatCount: 29 },
  { number: 49, name: "Al-Hujurat", ayatCount: 18 },
  { number: 50, name: "Qaf", ayatCount: 45 },
  { number: 51, name: "Adh-Dhariyat", ayatCount: 60 },
  { number: 52, name: "At-Tur", ayatCount: 49 },
  { number: 53, name: "An-Najm", ayatCount: 62 },
  { number: 54, name: "Al-Qamar", ayatCount: 55 },
  { number: 55, name: "Ar-Rahman", ayatCount: 78 },
  { number: 56, name: "Al-Waqi'ah", ayatCount: 96 },
  { number: 57, name: "Al-Hadid", ayatCount: 29 },
  { number: 58, name: "Al-Mujadila", ayatCount: 22 },
  { number: 59, name: "Al-Hasyr", ayatCount: 24 },
  { number: 60, name: "Al-Mumtahanah", ayatCount: 13 },
  { number: 61, name: "As-Saff", ayatCount: 14 },
  { number: 62, name: "Al-Jumu'ah", ayatCount: 11 },
  { number: 63, name: "Al-Munafiqun", ayatCount: 11 },
  { number: 64, name: "At-Taghabun", ayatCount: 18 },
  { number: 65, name: "At-Talaq", ayatCount: 12 },
  { number: 66, name: "At-Tahrim", ayatCount: 12 },
  { number: 67, name: "Al-Mulk", ayatCount: 30 },
  { number: 68, name: "Al-Qalam", ayatCount: 52 },
  { number: 69, name: "Al-Haqqah", ayatCount: 52 },
  { number: 70, name: "Al-Ma'arij", ayatCount: 44 },
  { number: 71, name: "Nuh", ayatCount: 28 },
  { number: 72, name: "Al-Jinn", ayatCount: 28 },
  { number: 73, name: "Al-Muzzammil", ayatCount: 20 },
  { number: 74, name: "Al-Muddassir", ayatCount: 56 },
  { number: 75, name: "Al-Qiyamah", ayatCount: 40 },
  { number: 76, name: "Al-Insan", ayatCount: 31 },
  { number: 77, name: "Al-Mursalat", ayatCount: 50 },
  { number: 78, name: "An-Naba", ayatCount: 40 },
  { number: 79, name: "An-Nazi'at", ayatCount: 46 },
  { number: 80, name: "'Abasa", ayatCount: 42 },
  { number: 81, name: "At-Takwir", ayatCount: 29 },
  { number: 82, name: "Al-Infitar", ayatCount: 19 },
  { number: 83, name: "Al-Mutaffifin", ayatCount: 36 },
  { number: 84, name: "Al-Insyiqaq", ayatCount: 25 },
  { number: 85, name: "Al-Buruj", ayatCount: 22 },
  { number: 86, name: "At-Tariq", ayatCount: 17 },
  { number: 87, name: "Al-A'la", ayatCount: 19 },
  { number: 88, name: "Al-Ghasyiyah", ayatCount: 26 },
  { number: 89, name: "Al-Fajr", ayatCount: 30 },
  { number: 90, name: "Al-Balad", ayatCount: 20 },
  { number: 91, name: "Asy-Syams", ayatCount: 15 },
  { number: 92, name: "Al-Lail", ayatCount: 21 },
  { number: 93, name: "Ad-Duha", ayatCount: 11 },
  { number: 94, name: "Asy-Syarh", ayatCount: 8 },
  { number: 95, name: "At-Tin", ayatCount: 8 },
  { number: 96, name: "Al-'Alaq", ayatCount: 19 },
  { number: 97, name: "Al-Qadr", ayatCount: 5 },
  { number: 98, name: "Al-Bayyinah", ayatCount: 8 },
  { number: 99, name: "Az-Zalzalah", ayatCount: 8 },
  { number: 100, name: "Al-'Adiyat", ayatCount: 11 },
  { number: 101, name: "Al-Qari'ah", ayatCount: 11 },
  { number: 102, name: "At-Takasur", ayatCount: 8 },
  { number: 103, name: "Al-'Asr", ayatCount: 3 },
  { number: 104, name: "Al-Humazah", ayatCount: 9 },
  { number: 105, name: "Al-Fil", ayatCount: 5 },
  { number: 106, name: "Quraisy", ayatCount: 4 },
  { number: 107, name: "Al-Ma'un", ayatCount: 7 },
  { number: 108, name: "Al-Kautsar", ayatCount: 3 },
  { number: 109, name: "Al-Kafirun", ayatCount: 6 },
  { number: 110, name: "An-Nasr", ayatCount: 3 },
  { number: 111, name: "Al-Lahab", ayatCount: 5 },
  { number: 112, name: "Al-Ikhlas", ayatCount: 4 },
  { number: 113, name: "Al-Falaq", ayatCount: 5 },
  { number: 114, name: "An-Nas", ayatCount: 6 },
]
